{ config, packages, pkgs, ... }:

{
  home.packages = [ pkgs.ripgrep ];

  programs.emacs = {
    extraPackages = epkgs: with epkgs; [
      aggressive-indent
      avy
      cape
      consult
      consult-eglot
      corfu
      delight
      editorconfig
      embark
      embark-consult
      evil
      evil-collection
      evil-commentary
      evil-surround
      expand-region
      general
      git-gutter
      helpful
      highlight-indent-guides
      just-mode
      magit
      marginalia
      nix-mode
      orderless
      rustic
      smartparens
      (treesit-grammars.with-grammars (p: [
        p.tree-sitter-tsx
        p.tree-sitter-typescript
        p.tree-sitter-yaml
      ]))
      ultra-scroll
      vertico
      which-key
      yaml-mode
    ];
  };

  xdg.configFile."emacs/lisp/turlando-utils.el".source =
    ./config/lisp/turlando-utils.el;
  xdg.configFile."emacs/lisp/turlando-fonts.el".text = ''
    ;;; turlando-fonts.el --- Font names from home-manager  -*- lexical-binding: t; -*-

    ;;; Commentary:
    ;;; Generated by home-manager.  Do not edit.

    ;;; Code:

    (defvar turlando/font-monospace "${config.fonts.families.monospace.family}-${toString config.fonts.families.monospace.size}")
    (defvar turlando/font-sans-serif "${config.fonts.families.sansSerif.family}-${toString config.fonts.families.sansSerif.size}")
    (defvar turlando/font-serif "${config.fonts.families.serif.family}-${toString config.fonts.families.serif.size}")

    (provide 'turlando-fonts)
    ;;; turlando-fonts.el ends here
  '';

  xdg.configFile."emacs/early-init.el".source = "${packages.minimal-emacs-d}/early-init.el";
  xdg.configFile."emacs/init.el".source = "${packages.minimal-emacs-d}/init.el";

  xdg.configFile."emacs/pre-early-init.el".source = ./config/pre-early-init.el;
  xdg.configFile."emacs/post-early-init.el".source = ./config/post-early-init.el;
  xdg.configFile."emacs/post-init.el".source = ./config/post-init.el;
}
